stages:
    - build
    - deploy 

before_script:
    - echo "$CI_REGISTRY"
    - echo "$CI_REGISTRY_USER"
    - echo "${CI_PROJECT_NAME}"
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}


Build docker image:
    stage: build
    script:
        - export COMPOSE="docker-compose -f docker-compose.build.yml"
        - $COMPOSE build
        - $COMPOSE push
    tags:
        - stage-shell

Deploy:
    stage: deploy
    script:
        - export COMPOSE="docker-compose -f docker-compose.yml"
        - $COMPOSE pull
        - $COMPOSE up --no-build -d --remove-orphans --force-recreate
    tags:
        - stage-shell
    only:
        - master
 

